# Generated by Django 3.2.6 on 2021-09-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_messages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
