# Generated by Django 3.2.6 on 2021-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_messages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
