# Generated by Django 3.2.6 on 2021-09-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_messages_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-datetime_created'], 'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
