# Generated by Django 3.2.7 on 2021-09-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210922_2144'),
        ('main', '0006_alter_messages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
